config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :user_logs, only: [:index, :show, :destroy]

  resources :units do
    collection do
      get 'import'
      post 'import' => 'units#import'
    end
    resources :users, :controller => 'unit_users'

    member do 
      # get 'index'
      get 'new_child_unit' => 'units#new'
      get 'child_units' => 'units#index'
      # get 'update_unit'
      # get 'destroy_unit'
    end
  end

  resources :users do
    member do
      get 'to_reset_pwd'
      patch 'reset_pwd'
      post 'lock' => 'users#lock'
      post 'unlock' => 'users#unlock'
    end
    resources :roles, :controller => 'user_roles'
  end

  resources :up_downloads do
    collection do 
      get 'up_download_import'
      post 'up_download_import' => 'up_downloads#up_download_import'
      
      get 'to_import'
      
      
    end
    member do
      get 'up_download_export'
      post 'up_download_export' => 'up_downloads#up_download_export'
    end
  end

  resources :expresses do
    collection do 
      get 'return_scan'
      post 'return_scan'
      post 'return_save'
      get 'resend_scan'
      post 'resend_scan'
      post 'find_resend_express_result'
      get 'tkzd'
      post 'tkzd'
      post 'get_new_express_no_and_print'
      get 'change_express_addr'
      post 'change_express_addr'
      get 'set_no_modify'
      post 'set_no_modify'
      get 'anomaly_done'
      post 'anomaly_done'
      get 'anomaly_index'
      post 'express_export'
      get 'set_failed'
      post 'set_failed'
    end
  end

  resources :batches do
    member do
      get 'done'
      post 'done' => 'batches#done'
    end
  end

  resources :orders do
    collection do 
      get 'change_order_addr'
      post 'change_order_addr'
      get 'set_no_modify'
      post 'set_no_modify'
    end
  end
    


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :unit, optional: true
  has_many :user_logs
  has_many :roles, dependent: :destroy

  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :lockable

  validates_presence_of :username, :name, :role, :message => '不能为空字符'#,

  validates_presence_of :unit_id, if: :unitadmin?

  validates_presence_of :unit_id, if: :user?
  
  validates_uniqueness_of :username, :message => '该用户已存在'

  validate :password_complexity

  ROLE = { superadmin: '超级管理员', unitadmin: '机构管理员', user: '普通用户' }
  STATUS_NAME = { locked: '已停用', unlocked: '已启用'}

  def status_name
    status.blank? ? "" : User::STATUS_NAME["#{status}".to_sym]
  end

  def rolename
    User::ROLE[role.to_sym]
  end

  def superadmin?
    (role.eql? 'superadmin') ? true : false
  end

  def unitadmin?
    (role.eql? 'unitadmin') ? true : false
  end

  def user?
    (role.eql? 'user') ? true : false
  end

  # def branch?
  #   self.unit.unit_type.eql? "branch"
  # end

  def email_required?
    false
  end

  def password_required?
    encrypted_password.blank? ? true : false
  end

  def password_complexity
    if password.present?
       if !password.match(/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,128}$/) 
         errors.add :password, "密码需同时包含英文字母和数字"
       end
    end
  end

  def is_unlocked?
    locked_at.blank?  ? true : false
  end
  
  def lock
    User.transaction do
      begin
        self.lock_access!
        self.update(locked_at: '3019-01-01')
        self.update(status: 'locked')
      rescue Exception => e
        raise e
      end
    end
  end

  def unlock
    User.transaction do
      begin
        self.unlock_access!
        self.update(status: 'unlocked')
      rescue Exception => e
        raise e
      end
    end  
  end
 
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create
  	puts "Users::SessionsController start"
    super do |resource|
      puts "test Users::SessionsController"
      # @user_log = UserLog.create(user: current_user, operation: '用户登录')

    end
    puts "Users::SessionsController end"
  end

  def destroy
  	# @user_log = UserLog.create(user: current_user, operation: '用户退出')
  	super do |resource|
  		# session[:current_storage] = nil
  	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource :user

  user_logs_filter only: [:create, :destroy], symbol: :username#, object: :user, operation: '新增用户'

  # GET /users
  # GET /users.json
  def index
    #@users = User.all
    @users_grid = initialize_grid(@users,
      :per_page => params[:page_size])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    #@user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    respond_to do |format|
      @user.role = 'user'
      if @user.save
        format.html { redirect_to @user, notice: I18n.t('controller.create_success_notice', model: '用户') }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: I18n.t('controller.update_success_notice', model: '用户') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def to_reset_pwd
  end

  def reset_pwd
    @operation = "reset_pwd"
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to request.referer, notice: "密码重置成功" }
        format.js { head :no_content }
      else
        format.html { render action: 'reset_pwd' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def lock
    @user.lock
  end

  def unlock
    @user.unlock  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_user
    #   @user = User.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user].permit(:username, :name, :password, :email, :unit_id,  :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
  <% if can? :role, @user %>
    <div class="control-group">
      <%= f.label :username, :class => 'control-label' %>
      <font color="red">(必填)</font>
      <div class="controls">
        <%= f.text_field :username, :class => 'text_field', :id => 'username' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <font color="red">(必填)</font>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field', :id => 'name' %>
      </div>
    </div>
  <% else %>
    <dl class="dl-horizontal">
      <dt><strong><%= f.label :username%></strong></dt>
      <font color="red">(必填)</font>
      <dd><%= @user.username %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><strong><%= f.label :name%></strong></dt>
      <font color="red">(必填)</font>
      <dd><%= @user.name %></dd>
    </dl>
  <% end %>
  
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <font color="red">(必填)</font>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field', :id => 'password' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field', :id => 'email' %>
    </div>
  </div>


  <% if can? :role, @user %>
    <div class="control-group">
      <%= f.label :unit_id, :class => 'control-label' %>
      <font color="red">(必选)</font>
     <div class="controls">
        <%= f.select(:unit_id, Unit.accessible_by(current_ability).map{|u| [u.name,u.id]}) %>
      </div> 
    </div>

    <div class="control-group">
      <%= f.label :role, :class => 'control-label' %>
      <font color="red">(必选)</font>
      <div class="controls">
        <%= f.select(:role, User::ROLE.invert.select{|k, v| (can? :role, v.to_sym)}) %>
      </div>
    </div>
  <% else %>
    <dl class="dl-horizontal">
      <dt><strong><%= f.label :unit_id%></strong></dt>
      <font color="red">(必选)</font>
      <dd><%= @user.unit.try :name %></dd>
    </dl>
    <dl class="dl-horizontal">
      <dt><strong><%= f.label :role%></strong></dt>
      <font color="red">(必选)</font>
      <dd><%= @user.rolename %></dd>
    </dl>
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <% if can? :index, User%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
<h1><%=t '.title', :default => [:'helpers.titles.index', '%{model} Manage'], :model => model_class.model_name.human.titleize %></h1>
  <%= render partial: '/layouts/page_size' %>
  <div style="float:right">
    <% if can? :new, User %>
      <%= link_to t('.new_user', :default => t("helpers.links.new_user")),
                  new_user_path,
                  :class => 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<%= grid(@users_grid) do |g|

    g.column name: model_class.human_attribute_name(:name), attribute: 'name'

    g.column name: model_class.human_attribute_name(:username), attribute: 'username'

    g.column name: model_class.human_attribute_name(:email), attribute: 'email' do |user|
      [user.email.try(:truncate, 10), {title: user.email}]
    end

    g.column name: model_class.human_attribute_name(:unit_id), attribute: 'unit_id' , allow_multiple_selection: false, custom_filter: Unit.accessible_by(current_ability).map{|u| [u.name,u.id]} do |user|
      [user.unit.try(:name).try(:truncate, 18), {title: user.unit.try(:name)}]
    end

    g.column name: model_class.human_attribute_name(:role), attribute: 'role' , allow_multiple_selection: false, custom_filter: User::ROLE.delete_if{|k| k.eql? :superadmin}.invert do |user| 
      user.rolename
    end

    g.column name: model_class.human_attribute_name(:status), attribute: 'status', allow_multiple_selection: false, custom_filter: User::STATUS_NAME.invert do |user| 
      user.status_name
    end

    g.column name: model_class.human_attribute_name(:created_at), attribute: 'created_at' do |user|
      l user.created_at
    end

    g.column do |user|
      ActiveSupport::SafeBuffer.new << 
        (link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-xs btn-primary' if can? :update, user) << ' ' <<
          (link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' if can? :destroy, user)<< ' ' <<
          (link_to t('.reset_pwd', :default => t("helpers.links.reset_pwd")), to_reset_pwd_user_path(user), :class => 'btn btn-xs btn-primary' if can? :reset_pwd, user)<< ' ' <<
          (link_to user.is_unlocked? ? "用户停用" : "用户启用",  user.is_unlocked? ? lock_user_path(user) :  unlock_user_path(user), :class => 'btn btn-xs btn-primary', :method => :post, name: "switch_user_status", remote: true,  data: { type: 'json' })
    end
  end 
%>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unit_id) %>:</strong></dt>
  <dd><%= @user.unit.try :name %></dd>
</dl>
<% if can? :index, User %>
<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<% end %>
<% if can? :update, @user %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<% end %>
<% if can? :destroy, @user %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>

app/views/users/to_reset_pwd.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%="重置密码" %></h1>
</div>
<%= form_for @user, :html => { :class => 'form-horizontal' }, :url => reset_pwd_user_path(@user) do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit "确定", :class => 'btn btn-primary' %>
    <% if can? :index, User%>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
    <% end %>
  </div>
<% end %>