config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :user_logs, only: [:index, :show, :destroy]

  resources :units do
    collection do
      get 'import'
      post 'import' => 'units#import'
    end
    resources :users, :controller => 'unit_users'

    member do 
      # get 'index'
      get 'new_child_unit' => 'units#new'
      get 'child_units' => 'units#index'
      # get 'update_unit'
      # get 'destroy_unit'
    end
  end

  resources :users do
    member do
      get 'to_reset_pwd'
      patch 'reset_pwd'
      post 'lock' => 'users#lock'
      post 'unlock' => 'users#unlock'
    end
    resources :roles, :controller => 'user_roles'
  end

  resources :up_downloads do
    collection do 
      get 'up_download_import'
      post 'up_download_import' => 'up_downloads#up_download_import'
      
      get 'to_import'
      
      
    end
    member do
      get 'up_download_export'
      post 'up_download_export' => 'up_downloads#up_download_export'
    end
  end

  resources :expresses do
    collection do 
      get 'return_scan'
      post 'return_scan'
      post 'return_save'
      get 'resend_scan'
      post 'resend_scan'
      post 'find_resend_express_result'
      get 'tkzd'
      post 'tkzd'
      post 'get_new_express_no_and_print'
      get 'change_express_addr'
      post 'change_express_addr'
      get 'set_no_modify'
      post 'set_no_modify'
      get 'anomaly_done'
      post 'anomaly_done'
      get 'anomaly_index'
      post 'express_export'
      get 'set_failed'
      post 'set_failed'
    end
  end

  resources :batches do
    member do
      get 'done'
      post 'done' => 'batches#done'
    end
  end

  resources :orders do
    collection do 
      get 'change_order_addr'
      post 'change_order_addr'
      get 'set_no_modify'
      post 'set_no_modify'
    end
  end
    


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :users, dependent: :destroy
  belongs_to :parent_unit, :class_name => 'Unit', :foreign_key => 'parent_id', optional: true
  has_many :child_units, :class_name => 'Unit', :foreign_key => 'parent_id',:dependent => :destroy

  before_save :set_level
  # has_many :tarrif_items, dependent: :destroy
  # has_many :tarrif_packages, dependent: :destroy

  validates_presence_of :name, :message => '不能为空'
  validates_uniqueness_of :name, :message => '该单位已存在'

  validates_uniqueness_of :short_name, :message => '该缩写已存在', if: :short_name?

  validates_presence_of :parent_id, :message => '不能为空', unless: :is_parent?

  LEVEL = {1 => 1, 2 => 2}
  # TYPE = {branch: '区分公司', delivery: '寄递事业部', postbuy: '国际邮购'}
  # TYPE_BRANCH = {branch: '区分公司'}
  # DELIVERY = Unit.find_by(unit_type: 'delivery') 
  # POSTBUY = Unit.find_by(unit_type: 'postbuy') 
  def unit_type_name
    unit_type.blank? ? "" : self.class.human_attribute_name("unit_type_#{unit_type}")
  end
  
  
  def can_destroy?
		if self.child_units.blank? && self.users.blank?
			return true
		else
			return false
		end
  end

  def is_parent?
    unit_level.blank? || unit_level <= 1 
  end

  def set_level
    if ! parent_unit.blank?
      self.unit_level = (parent_unit.unit_level||1) + 1
    else
      self.unit_level = 1
    end
  end
  # def delivery?
  #   (unit_type.eql? 'delivery') ? true : false
  # end
  # def postbuy?
  #   (unit_type.eql? 'postbuy') ? true : false
  # end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  load_and_authorize_resource :unit

  # GET /units
  # GET /units.json
  def index
    #@unit = Unit.all
    @units_grid = initialize_grid(@units.where(parent_id: params[:id]), :per_page => params[:page_size])
  end

  # def child_units
  #   @parentid = params[:id]
  #   @unit = Unit.new
  # end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    # @parent_id = params[:id]
    # @parent_unit = Unit.find(@parent_id) if ! @parent_id.blank?
    @unit.parent_id = params[:id]
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      # @unit.unit_type = 'branch'
       if @unit.save
        format.html { redirect_to @unit, notice: I18n.t('controller.create_success_notice', model: '单位')}
        format.json { render action: 'show', status: :created, location: @unit }
      else
        format.html { render action: 'new' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params_4_update)
        format.html { redirect_to @unit, notice: I18n.t('controller.update_success_notice', model: '单位') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    if @unit.can_destroy?
      @unit.destroy
    else
      flash[:alert] = " 该区分公司下存在用户，不可删除。"
    end
    respond_to do |format|
      format.html { redirect_to units_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_unit
      #@unit = Unit.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:no, :name, :desc, :short_name, :unit_level, :parent_id, :unit_type)
    end

    def unit_params_4_update
      params.require(:unit).permit(:no, :name, :desc, :short_name, :unit_type)
    end
end

app/views/units/_form.html.erb
<%= form_for @unit, :html => { :class => 'form-horizontal' } do |f| %>
  <% @unit.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
  <% end %>
 
  <div class="control-group">
    <%= f.label :no, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :no, :class => 'text_field', :id => 'no' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <font color="red">(必填)</font>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', :id => 'name' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :short_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :short_name, :class => 'text_field', :id => 'short_name' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :desc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :desc, :class => 'text_field', :id => 'desc' %>
    </div>
  </div>
  <% if ! @unit.parent_id.blank?%>
    <% if ! @unit.persisted? %>
      <%= hidden_field(:unit, :parent_id, {value: @parent_id||@unit.parent_id})%>
    <% end %>
  <div class="control-group">
    <%= f.label :parent_unit, :class => 'control-label' %>
    <div class="controls">
      <%= @parent_unit.try(:name) || @unit.parent_unit.try(:name)%>
    </div>
  </div>
  <% end %>

  <!-- <div class="control-group">
    <%= f.label :parent_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:parent_id, Unit.where("unit_level in (1,2)").order(:unit_level,:id).map{|u| [u.name,u.id]})%>
    </div>
  </div>
   -->
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            units_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/units/edit.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/import.html.erb
<center>
<br><br>
<font face="微软雅黑" color='#006030' size=6>机构导入</font>   

<br><br><br>
  
 	
<%= form_tag({:action => 'import'}, :multipart => true, name: 'form1') %>
<!--<font face="微软雅黑" color='#D9B300' size=3>上传文档模板: <%= file_field("file", "file",:onclick=>'enable_submit_tag()') %></font>  -->
<font face="微软雅黑" color='#D9B300' size=3>上传文档模板: <%= file_field("file", "file",onclick: "$('#submit_button').removeAttr('disabled');") %></font>  
<br><br><br>


<!--<%= submit_tag "确认导入",:id=>'submit_button', data: { disable_with: "导入中，请稍等..." } %>-->
<%= submit_tag "确认导入",:id=>'submit_button',onclick: "form1.submit();this.disabled='disabled';" %>
</form>

</center>

app/views/units/index.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.index', '%{model} Manage'], :model => model_class.model_name.human.titleize %></h1>
  <%= render partial: '/layouts/page_size' %>
  
  <!--% if current_user.unit.blank? or current_user.unit.unit_level == 1 %-->
  <% if ! params[:id].blank? %>
  <div style="float:right">
    <% if can? :new, Unit %>
      <%= link_to t("新增下级单位"), new_child_unit_unit_path(params[:id]), :class => 'btn btn-primary' %>
    <% end %>

    <%= link_to t('.back', :default => t("helpers.links.back")),
                  units_path,
                  :class => 'btn btn-primary' %> 
  </div>
  <br>
  <% else %>
  <div style="float:right">
    <% if can? :new, Unit %>
      <%= link_to t('.new_unit', :default => t("helpers.links.new_unit")),
                  new_unit_path,
                  :class => 'btn btn-primary' %>
    <% end %>
  </div>
  <br>
  <% end %>
  <!--% end %-->
</div>


<%= grid(@units_grid) do |g|
  g.column name: model_class.human_attribute_name(:no), attribute: 'no'

  g.column name: model_class.human_attribute_name(:name), attribute: 'name'  do |unit|
    [unit.name.try(:truncate, 18), {title: unit.name}] end

  g.column name: model_class.human_attribute_name(:short_name), attribute: 'short_name'

  g.column name: model_class.human_attribute_name(:desc), attribute: 'desc'  do |unit|
    [unit.desc.try(:truncate, 18), {title: unit.desc}]
  end


  g.column name: model_class.human_attribute_name(:unit_level), attribute: 'unit_level', custom_filter: Unit::LEVEL.invert,  allow_multiple_selection: false  do |unit| 
    unit.unit_level
  end

  g.column name: model_class.human_attribute_name(:unit_type), attribute: 'unit_type', allow_multiple_selection: false do |unit| 
    unit.unit_type
  end
  
  g.column name: model_class.human_attribute_name(:parent_unit), attribute: 'parent_id' ,custom_filter: Unit.where(unit_level: 1).accessible_by(current_ability).map{|u| [u.name,u.id]}, allow_multiple_selection: false do |unit|
      unit.parent_unit.try(:name)
  end
  
  
  g.column name: model_class.human_attribute_name(:created_at), attribute: 'created_at' do |unit|
    l unit.created_at
  end

  g.column do |unit|
    ActiveSupport::SafeBuffer.new << 
      (link_to t("新增下级单位"), new_child_unit_unit_path(unit), :class => 'btn btn-xs btn-primary' if (can? :create, unit) && (unit[:unit_level].eql? 1)) << ' ' << 
      (link_to t('.edit', :default => t("helpers.links.edit")), edit_unit_path(unit), :class => 'btn btn-xs btn-primary' if can? :update, unit) << ' ' <<
      (link_to t('.destroy', :default => t("helpers.links.destroy")), unit_path(unit), :method => :delete, :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => '确定删除?')) }, :class => 'btn btn-xs btn-danger' if can? :destroy, unit) << ' ' <<
      (link_to t('.users', :default => t("helpers.links.users")), unit_users_path(unit), :class => 'btn btn-xs btn-info' if can? :user, unit) << ' ' << 
      (link_to "下级单位", child_units_unit_path(unit), :class => 'btn btn-xs btn-primary' if (can? :read, unit) && (unit[:unit_level].eql? 1))
  end
end
%>

app/views/units/new.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/newsub.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/units/select_level3_parents.js.erb
$('#level3_parent_id').html(" <%= escape_javascript options_for_select(@level3_parents) %> ");

app/views/units/show.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:no) %>:</strong></dt>
  <dd><%= @unit.no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @unit.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_name) %>:</strong></dt>
  <dd><%= @unit.short_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desc) %>:</strong></dt>
  <dd><%= @unit.desc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:unit_level) %>:</strong></dt>
  <dd><%= @unit.unit_level %></dd>
  <dt><strong><%= model_class.human_attribute_name(:parent_unit) %>:</strong></dt>
  <dd><%= @unit.parent_unit.try(:name) %></dd>
 <!--  <dt><strong><%= model_class.human_attribute_name(:parent_id) %>:</strong></dt>
  <dd><%= @unit.parent_id.blank? ? "" : Unit.find_by(id:@unit.parent_id).name %></dd> -->
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              units_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_unit_path(@unit), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              unit_path(@unit),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '确定删除?')) },
              :class => 'btn btn-danger' %>

app/views/units/update_unit.html.erb
<%- model_class = Unit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<div>
   <%= form_tag("/units/update_unit_info", method: "post")%>
   <%= hidden_field_tag('unitid',@unit.id)%>
  <div class="control-group">
      <%= label_tag(:no, "编号") %>
      <div class="controls">
      <%= text_field_tag(:no,@unit.no) %>
      </div>
  </div>
	<div class="control-group">
      <%= label_tag(:name, "单位名称") %>
      <div class="controls">
      <%= text_field_tag(:name,@unit.name) %>
      </div>
  </div>
	<div class="control-group">
      <%= label_tag(:short_name, "英文缩写") %>
      <div class="controls">
      <%= text_field_tag(:short_name,@unit.short_name) %>
      </div>
  </div>
	<div class="control-group">
      <%= label_tag(:unit_desc, "单位描述") %>
      <div class="controls">
      <%= text_field_tag(:unit_desc,@unit.unit_desc) %>
      </div>
  </div>
  <div class="control-group">
      <%= label_tag(:tcbd_khdh, "商务投递客户编号") %>
      <div class="controls">
      <%= text_field_tag(:tcbd_khdh,@unit.tcbd_khdh) %>
	    </div>
  </div>
   <% if !@unit.parent.blank? and @unit.parent.name.eql?I18n.t("relevant_unit.parent") %>
    <div class="control-group">
    <%= check_box_tag 'is_facility_management_unit' %>是否为设备管理单位
    </div>
   <% end %>
  
  <div>
    <%= submit_tag "更新单位管理",:class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            units_path, :class => 'btn btn-default' %>
  </div>
   </form>
</div>