config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :user_logs, only: [:index, :show, :destroy]

  resources :units do
    collection do
      get 'import'
      post 'import' => 'units#import'
    end
    resources :users, :controller => 'unit_users'

    member do 
      # get 'index'
      get 'new_child_unit' => 'units#new'
      get 'child_units' => 'units#index'
      # get 'update_unit'
      # get 'destroy_unit'
    end
  end

  resources :users do
    member do
      get 'to_reset_pwd'
      patch 'reset_pwd'
      post 'lock' => 'users#lock'
      post 'unlock' => 'users#unlock'
    end
    resources :roles, :controller => 'user_roles'
  end

  resources :up_downloads do
    collection do 
      get 'up_download_import'
      post 'up_download_import' => 'up_downloads#up_download_import'
      
      get 'to_import'
      
      
    end
    member do
      get 'up_download_export'
      post 'up_download_export' => 'up_downloads#up_download_export'
    end
  end

  resources :expresses do
    collection do 
      get 'return_scan'
      post 'return_scan'
      post 'return_save'
      get 'resend_scan'
      post 'resend_scan'
      post 'find_resend_express_result'
      get 'tkzd'
      post 'tkzd'
      post 'get_new_express_no_and_print'
      get 'change_express_addr'
      post 'change_express_addr'
      get 'set_no_modify'
      post 'set_no_modify'
      get 'anomaly_done'
      post 'anomaly_done'
      get 'anomaly_index'
      post 'express_export'
      get 'set_failed'
      post 'set_failed'
    end
  end

  resources :batches do
    member do
      get 'done'
      post 'done' => 'batches#done'
    end
  end

  resources :orders do
    collection do 
      get 'change_order_addr'
      post 'change_order_addr'
      get 'set_no_modify'
      post 'set_no_modify'
    end
  end
    


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/expresses_controller.rb
class ExpressesController < ApplicationController
  load_and_authorize_resource :express
  protect_from_forgery :except => [:tkzd]

  # 邮件管理
  def index
  	if !params[:batch_id].blank?
  		@expresses = Express.where(batch_id: params[:batch_id]).order("scaned_at desc")
  	end
  	
    @expresses_grid = initialize_grid(@expresses.order("scaned_at desc"),
      :per_page => params[:page_size],
      name: 'expresses'
      # ,
      # :enable_export_to_csv => true,
      # :csv_file_name => 'expresses',
      # :csv_encoding => 'gbk'
      )
    # export_grid_if_requested
  end

  # 异常邮件处理
  def anomaly_index
		@expresses = Express.where(anomaly: true, removed: false).order("scaned_at desc, express_no asc")
	  
    @expresses_grid = initialize_grid(@expresses,
         :per_page => params[:page_size])
  end

  def edit
  end

  def show
  end

  def update
    respond_to do |format|
      if !express_params[:receiver_province].blank? && !express_params[:receiver_city].blank? && !express_params[:receiver_district].blank?
      	if @express.update(express_params)
          format.html { redirect_to @express, notice: I18n.t('controller.update_success_notice', model: '邮件')}
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @express.errors, status: :unprocessable_entity }
        end
      else
        flash[:alert] = "收件人省市区不能为空"
        format.html { render action: 'edit' }
        format.json { render json: @express.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @express.status.eql?"waiting"
      @express.destroy
    else
      flash[:alert] = " 该邮件不可删除。"
    end
    respond_to do |format|
      format.html { redirect_to expresses_url }
      format.json { head :no_content }
    end
  end

  # 打印
  def tkzd
  	@result = []
  	@express_id = params[:express_id]
 	
  	if !@express_id.blank?
  		@result << Express.find(@express_id)
  	else
	  	if !params[:expresses].blank? && !params[:expresses][:selected].blank?
	      # selected = params[:expresses][:selected].split(",")
        selected = params[:expresses][:selected]
	       
	      until selected.blank? do 
	        @result += Express.where.not(new_express_no: nil, route_code: nil).where(id:selected.pop(1000), status: ["done", "feedback"])
	      end
      else
	      flash[:alert] = "请勾选需要打印的邮件"
	      respond_to do |format|
	        format.html { redirect_to request.referer }
	        format.json { head :no_content }
	      end
	    end
    end
  end

  # 退件扫描
  def return_scan
  end

  # 退件扫描,保存
  def return_save
  	if !params["batch_name"].blank? && !params["scaned_nos"].blank?
  		scaned_nos = params["scaned_nos"].split(",")
  		batch = Batch.create! name: params["batch_name"], status: "waiting", operator1: current_user.id
  		scaned_nos.each do |s|
  			batch.expresses.create! express_no: s, scaned_at: Time.now, status: "waiting", operator1: current_user.id, sender_province: "上海", sender_city: "上海", sender_district: "浦东新区", sender_addr: "上海浦东新区上海邮政120-058信箱", sender_name: "招商银行信用卡中心", sender_phone: "4008205555"
  		end
  	end
  	flash[:notice] = "保存成功"		
  	redirect_to request.referer
  end

  # 重寄扫描
  def resend_scan
  	@express = nil
  end

  # 重寄扫描,查询邮件号
  def find_resend_express_result
  	@resend_express_no = params[:resend_express_no]
  	@express = Express.find_by(status: "pending", express_no: @resend_express_no)
  	@deal_require = ""

  	if @express.blank?
  		@deal_require = "not_found"
  	else
      # 03退回卡厂,05退回卡厂成功
      if @express.deal_require.eql?"03"
        @deal_require = "03"
        @express.update status: "done", deal_result: "05", operator2: current_user.id, scaned_at: Time.now
      else
    		if !@express.address_status.eql?"address_success"
    			@deal_require = "address_failed"
    		else
    			@deal_require = @express.deal_require  			
    		end
      end
  	end
  end

  # 取新邮件号,格口码并跳转打印
  def get_new_express_no_and_print
  	deal_result = ""
  	last_express_no = params[:last_express_no]

  	if !last_express_no.blank?
  		@express = Express.find_by(status: "pending", address_status: "address_success", express_no: last_express_no)
  		@msg = express_send(@express)

  		# deal_require: 01(改址重寄), 02(原地址重寄), 03(退回卡厂)
  		# deal_result: 01(已改址重寄), 02(重寄失败), 03(已原地址寄送), 04(重寄失败), 05(退回卡厂成功), 06(退回卡厂失败)
  		if @msg.eql?"成功"
	    	if @express.deal_require.eql?"01"
	    		deal_result = "01"
	    	elsif @express.deal_require.eql?"02"
	    		deal_result = "03"
	    	end
	    			
	    	@express.update status:"done", deal_result: deal_result, operator2: current_user.id, scaned_at: Time.now
	    end
	  end
  end

  # 邮件改址
  def change_express_addr
  	@expresses = @expresses.accessible_by(current_ability).where(status: "pending").where(no_modify: false)

  	# 筛选异地邮件
    if !params[:abnormal].blank? && (params[:abnormal].eql?"true")
      @expresses = @expresses.where("(receiver_province not like (?) or ((receiver_province is ? or receiver_city is ? or receiver_district is ?) and address_status = ?) or address_status= ?) and no_modify = ?", "上海%", nil, nil, nil, "address_success", "address_failed", false)
    end

    @expresses_grid = initialize_grid(@expresses,
         :order => 'express_no',
         :order_direction => 'asc', 
         :per_page => params[:page_size])
  end

  # 邮件改址,无需修改
  def set_no_modify
    if params[:grid] && params[:grid][:selected]
      selected = params[:grid][:selected]
         
      until selected.blank? do 
        expresses = Express.where(id:selected.pop(1000)).where.not(receiver_province: nil).where.not(receiver_city: nil).where.not(receiver_district: nil)
        expresses.each do |o|
          o.update no_modify: true, address_status: "address_success"
        end
      end
      flash[:notice] = "已设置成功"      
    else
      flash[:alert] = "请勾选邮件"
    end   
    
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
  end

	# 发送新一代接口，获取邮件号，格口码,返回'成功'或出错信息
	def express_send(express)
		interface_sender = XydInterfaceSender.order_create_interface_sender_initialize(express)
		interface_sender.interface_send(10)
		msg = XydInterfaceSender.get_response_message(interface_sender)
		# express.update new_express_no: "0000004", route_code: "0000004"
		# msg = "成功"
		return msg			
	end

	# 异常邮件处理,异常处理完成
	def anomaly_done
		expresses = []

		if params[:grid] && params[:grid][:selected]
  		selected = params[:grid][:selected]
	       
	    until selected.blank? do 
	      expresses = Express.where(id:selected.pop(1000))
	      expresses.each do |e|
	      	e.update status: "cancelled", removed: true
	      end
	    end
	    flash[:notice] = "异常处理完成"	    
	  else
	  	flash[:alert] = "请勾选邮件"
	  end   
	  
  	respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
	end

  def express_export
    expresses = filter_expresses(@expresses,params)
    
    if expresses.blank?
      flash[:alert] = "无数据"
      redirect_to :action => 'index'
    else
      send_data(express_xls_content_for(expresses.order("scaned_at desc")), :type => "text/excel;charset=utf-8; header=present", :filename => "数据_#{Time.now.strftime("%Y%m%d")}.xls")  
    end
  end

  def filter_expresses(expresses, params)
    start_date = nil
    end_date = nil
    expresses = expresses.left_joins(:batch)

    if !params[:expresses].blank?
      if !params[:expresses][:f].blank?
        params_f = params[:expresses][:f]
        if !params_f[:express_no].blank?
          expresses = expresses.where("express_no like ?", '%'+params_f[:express_no]+'%')
        end

        if !params_f[:scaned_at][:fr].blank?
          start_date = params_f[:scaned_at][:fr] 
          expresses = expresses.where("scaned_at >= ?", start_date)
        end

        if !params_f[:scaned_at][:to].blank?
          end_date = params_f[:scaned_at][:to].to_date+1.day 
          expresses = expresses.where("scaned_at < ?", end_date)
        end

        if !params_f['batches.name'].blank?
          batch_name = params_f['batches.name']
          expresses = expresses.where("batches.name like ?", '%'+batch_name+'%')
        end
        
        if !params_f[:anomaly][0].blank?
          expresses = expresses.where(anomaly: params_f[:anomaly][0])
        end

        if !params_f[:status].blank?
          if !params_f[:status][0].blank?
            expresses = expresses.where(status: params_f[:status][0])
          end
        end

        if !params_f[:deal_require].blank?
          if !params_f[:deal_require][0].blank?
            expresses = expresses.where(deal_require: params_f[:deal_require][0])
          end
        end

        if !params_f[:deal_result].blank?
          if !params_f[:deal_result][0].blank?
            expresses = expresses.where(deal_result: params_f[:deal_result][0])
          end
        end

        if !params_f[:new_express_no].blank?
          expresses = expresses.where("new_express_no like ?", '%'+params_f[:new_express_no]+'%')
        end

        if !params_f[:receiver_name].blank?
          expresses = expresses.where("receiver_name like ?", '%'+params_f[:receiver_name]+'%')
        end

        if !params_f[:receiver_phone].blank?
          expresses = expresses.where("receiver_phone like ?", '%'+params_f[:receiver_phone]+'%')
        end

        if !params_f[:receiver_addr].blank?
          expresses = expresses.where("receiver_addr like ?", '%'+params_f[:receiver_addr]+'%')
        end

        if !params_f[:receiver_postcode].blank?
          expresses = expresses.where("receiver_postcode like ?", '%'+params_f[:receiver_postcode]+'%')
        end

        if !params_f[:operator1].blank?
          if !params_f[:operator1][0].blank?
            expresses = expresses.where(operator1: params_f[:operator1][0])
          end
        end

        if !params_f[:operator2].blank?

app/views/expresses/_expresses_grid.html.erb
<%- model_class = Express -%>

<%= grid(@expresses_grid) do |g|
    g.action_column select_all_buttons: true #do |express|
    #   !express.new_express_no.blank? && !express.route_code.blank? && (["done", "feedback"].include?express.status)
    # end 

    g.column name: model_class.human_attribute_name(:express_no), attribute: 'express_no'

    g.column name: model_class.human_attribute_name(:scaned_at), attribute: 'scaned_at' do |express|
      express.scaned_at.blank? ? "" : express.scaned_at.strftime('%Y-%m-%d %H:%M:%S')
    end

    g.column name: model_class.human_attribute_name(:batch_id), attribute: 'batch_id', assoc: :batch, attribute: 'name'

    g.column name: model_class.human_attribute_name(:anomaly), attribute: 'anomaly' do |express| 
      express.anomaly? ? '是' : '否'
    end

    g.column name: model_class.human_attribute_name(:status), attribute: 'status',custom_filter: Express::STATUS_NAME.invert do |express| 
      express.status_name
    end

    g.column name: model_class.human_attribute_name(:deal_require), attribute: 'deal_require',custom_filter: Express::DEAL_REQUIRE_NAME.invert do |express| 
      express.deal_require_name
    end

    g.column name: model_class.human_attribute_name(:deal_result), attribute: 'deal_result',custom_filter: Express::DEAL_RESULT_NAME.invert do |express| 
      express.deal_result_name
    end

    g.column name: model_class.human_attribute_name(:new_express_no), attribute: 'new_express_no'

    g.column name: model_class.human_attribute_name(:receiver_name), attribute: 'receiver_name'

    g.column name: model_class.human_attribute_name(:receiver_phone), attribute: 'receiver_phone'

    g.column name: model_class.human_attribute_name(:receiver_addr), attribute: 'receiver_addr'

    g.column name: model_class.human_attribute_name(:receiver_postcode), attribute: 'receiver_postcode'

    g.column name: model_class.human_attribute_name(:operator1), attribute: 'operator1', custom_filter: User.where.not(role: 'superadmin').map{|u| [u.name,u.id]}, allow_multiple_selection: false do |express|
      express.operator1.blank? ? "" : User.find(express.operator1).name
    end

    g.column name: model_class.human_attribute_name(:operator2), attribute: 'operator2', custom_filter: User.where.not(role: 'superadmin').map{|u| [u.name,u.id]}, allow_multiple_selection: false do |express|
      express.operator2.blank? ? "" : User.find(express.operator2).name
    end

    g.column do |express|
      ActiveSupport::SafeBuffer.new << 
        (link_to t('.destroy', :default => t("helpers.links.destroy")), express_path(express), :method => :delete, :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => '确定删除?')) }, :class => 'btn btn-xs btn-danger' if (can? :destroy, express) && (express.status.eql?"waiting"))
    end

  end 
  %>

app/views/expresses/_form.html.erb
<%= form_for @express, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :express_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :express_no, :class => 'text_field', disabled: true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :receiver_province, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :receiver_province, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :receiver_city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :receiver_city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :receiver_district, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :receiver_district, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :receiver_addr, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :receiver_addr, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :receiver_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :receiver_name, :class => 'text_field', disabled: true %>
    </div>
  </div>
   <div class="control-group">
    <%= f.label :receiver_phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :receiver_phone, :class => 'text_field', disabled: true %>
    </div>
  </div>
  
  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <% if can? :change_express_addr, Express %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              change_express_addr_expresses_path, :class => 'btn btn-default' %>
  <% end %>
<% end %>

app/views/expresses/_resend_scan_form.html.erb
<% if !@express.blank? %>
<table class="table table-striped"> 
	<thead>
		<tr>
			<th>原运单号</th>
			<th>处理方式</th>
			<th>收件人地址</th>
			<th>收件人姓名</th>
			<th>收件人电话</th>
		</tr>
	</thead>
	<tbody>
		<tr>
	  	<td><%= @express.express_no %></td>
	  	<td><%= @express.deal_require_name %></td>
	  	<td><%= @express.receiver_addr %></td>
	  	<td><%= @express.receiver_name %></td>
	  	<td><%= @express.receiver_phone %></td>
	  </tr>
	</tbody>
</table>
<% end %>

app/views/expresses/anomaly_index.html.erb
<%- model_class = Express -%>
<div class="page-header">
<h1>异常邮件处理</h1>
  <%= render partial: '/layouts/page_size' %>
  <div style="float:right">
    <% if can? :anomaly_done, Express %>
    <%= submit_tag "异常处理完成",:class => 'btn btn-primary', onclick: "form1.action='anomaly_done';form1.submit();" %>
    <% end %>
  </div>
</div> 

<div>
<%= form_tag('', :method => "post", name: 'form1') do %>
  <%= grid(@expresses_grid) do |g|
    g.action_column select_all_buttons: true

    g.column name: model_class.human_attribute_name(:express_no), attribute: 'express_no'

    g.column name: model_class.human_attribute_name(:scaned_at), attribute: 'scaned_at' do |express|
      express.scaned_at.blank? ? "" : express.scaned_at.strftime('%Y-%m-%d %H:%M:%S')
    end

    g.column name: model_class.human_attribute_name(:anomaly_desc), attribute: 'anomaly_desc'

    g.column name: model_class.human_attribute_name(:batch_id), attribute: 'batch_id', assoc: :batch, attribute: 'name'

  end 
  %>
<% end %>
</div>

app/views/expresses/change_express_addr.html.erb
<%- model_class = Express -%>
<div class="page-header">
<h1>邮件改址</h1>
  <div><%= render partial: '/layouts/page_size' %></div>
</div>
<div align='right'>
  <%= submit_tag "无需修改",:class => 'btn btn-primary', onclick: "form1.action='set_no_modify';form1.submit();" %>
  <%= submit_tag "筛选异地邮件",:class => 'btn btn-primary', onclick: "form1.action='change_express_addr?abnormal=true';form1.submit();" %>
</div>


<%= form_tag('', name: 'form1') do %>
<%= grid(@expresses_grid) do |g|
  g.action_column select_all_buttons: true

	g.column name: model_class.human_attribute_name(:express_no), attribute: 'express_no'

	g.column name: model_class.human_attribute_name(:receiver_province), attribute: 'receiver_province'

	g.column name: model_class.human_attribute_name(:receiver_city), attribute: 'receiver_city'

	g.column name: model_class.human_attribute_name(:receiver_district), attribute: 'receiver_district'

	g.column name: model_class.human_attribute_name(:receiver_addr), attribute: 'receiver_addr'

	g.column name: model_class.human_attribute_name(:receiver_name), attribute: 'receiver_name'

	g.column name: model_class.human_attribute_name(:receiver_phone), attribute: 'receiver_phone'

	g.column name: "邮件日期", attribute: 'created_at' do |express|
    l express.created_at
  end

  g.column name: model_class.human_attribute_name(:address_status), attribute: 'address_status',custom_filter: Express::ADDRESS_STATUS_NAME.invert do |express| 
      express.address_status_name
    end

  g.column do |express|
    ActiveSupport::SafeBuffer.new << 
    (link_to t('.edit', :default => t("helpers.links.edit")), edit_express_path(express), target: '_blank', :class => 'btn btn-xs btn-primary' if (can? :update, express))
  end

end 
%>
<% end %>

app/views/expresses/edit.html.erb
<%- model_class = Express -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/expresses/find_resend_express_result.js.erb
$('#resend_express_no').blur();
<% if @deal_require.eql?"not_found" %>
	var audio = document.getElementById("not_found_alert");
	audio.play();
	$('#last_express_no').val("");
<% elsif @deal_require.eql?"address_failed" %>
	var audio = document.getElementById("address_failed_alert");
	audio.play();
	$('#last_express_no').val("");
<% elsif @deal_require.eql?"03" %>
	var audio = document.getElementById("return_alert");
	audio.play();
	$('#last_express_no').val("");
<% elsif ["01", "02"].include?@deal_require %>
	var audio = document.getElementById("resend_alert");
	audio.play();
	if(confirm("邮件需重寄")){
		$('#last_express_no').val("<%= @resend_express_no %>");
		if($('#last_express_no').val() != ""){
			$('#resend_express_no').blur();
			showMask();
			get_new_express_no_and_print();
			$('#resend_express_no').attr("disabled","disabled");
		}
	}
	
	// if(confirm("是否打印面单？")){
	// 	window.open("../expresses/tkzd?express_id="+<%= Express.find_by(express_no: @resend_express_no).id %>);
	// 	$('#resend_express_no').blur();
	// 	showMask();
	// 	$('#resend_express_no').attr("disabled","disabled");
	// }
<% end %>
$('#resend_express_no').val("");
$('#resend_out_results').html(" <%= escape_javascript(render(:partial => 'expresses/resend_scan_form')) %> ");
$('#new_express_no').text("");
$('#route_code').text("");
$('#resend_express_no').focus();

function showMask(){
	document.getElementById('mid').style.display="block";
}

function get_new_express_no_and_print(){
	$.ajax({
					type : 'POST',
					url : '../expresses/get_new_express_no_and_print/',
					data: { last_express_no: $('#last_express_no').val()},
					dataType : 'script'
				});
}

app/views/expresses/get_new_express_no_and_print.js.erb
document.getElementById('mid').style.display='none';
$('#resend_express_no').removeAttr('disabled');
$('#resend_express_no').val("");
$('#resend_express_no').focus();
<% if @msg.eql?"成功" %>
	window.open("../expresses/tkzd?express_id="+<%= @express.id %>);
	$('#new_express_no').text("");
	$('#route_code').text("");
	$('#resend_out_results').html("");
	$('#last_express_no').val("");
<% else %>
	alert("<%= @msg %>");
<% end %>

app/views/expresses/index.html.erb
<%- model_class = Express -%>
<div class="page-header">
<h1><%=t '.title', :default => [:'helpers.titles.index', '%{model} Manage'], :model => model_class.model_name.human.titleize %></h1>
<%= render partial: '/layouts/page_size' %>

<br>
<%= form_tag('', :method => "post", name: 'form1') do %>
<div style="float:right">
<%= button_tag "置为失败",:class => 'btn btn-primary', onclick: "if(confirm('确定将所有勾选邮件的处理结果置为失败？')){form1.action='expresses/set_failed';form1.submit();}" %>
<% if can? :tkzd, Express %>
<%= button_tag "打印面单", :class => 'btn btn-primary', target: '_blank', onclick: "form1.action='expresses/tkzd';form1.submit();" %>
<% end %>
<%= button_tag "导出",:class => 'btn btn-primary', onclick: "form1.action='expresses/express_export.xls';form1.submit();" %>
<!-- <button class="btn btn-primary wg-external-csv-export-button" data-grid-name="expresses">导出</button> -->
</div>
<br>

<%= render partial: 'expresses_grid' %>
<% end %>
</div> 

app/views/expresses/resend_scan.html.erb
<div class="page-header">
  <h1>二次扫描</h1>
</div>
<%= form_tag('', name: 'form1') do -%>
<%= hidden_field_tag('last_express_no', '') %>
<audio src="<%=asset_path("resend.mp3")%>" id="resend_alert"></audio>
<audio src="<%=asset_path("return.mp3")%>" id="return_alert"></audio>
<audio src="<%=asset_path("not_found.mp3")%>" id="not_found_alert"></audio>
<audio src="<%=asset_path("address_failed.mp3")%>" id="address_failed_alert"></audio>
<div>
	<table>
		<tr class= 'nowrap'>
 			<td><h4>邮件号: <%= text_field_tag 'resend_express_no', nil, class: "controls showmask", size: "30", :id => "resend_express_no", maxlength: 13, :disabled => false %></h4></td>
 			<td><%= button_tag "重置",:class => 'btn btn-primary', :id => "reset", :type => "button"%></td>
 			<!-- <td><%= button_tag "打印面单",:class => 'btn btn-primary', :id => "tkzd", :disabled => true, onclick: "window.open('/packages/tkzd', '_blank');" %></td> -->
			<td></td>
			<td><font color="green"><h3><%= label_tag 'new_express_no', "", class: 'control-group', :id => "new_express_no" %></h3></font></td>
			<td><font color="green"><h3><%= label_tag 'route_code', "", class: 'control-group', :id => "route_code" %></h3></font></td>
		</tr>
	</table>
</div>
<div id="resend_out_results">
  <%= render :partial => 'expresses/resend_scan_form' %>
</div>
<% end %>

app/views/expresses/return_scan.html.erb
<div class="page-header">
  <h1>退件扫描</h1>
</div>
<%= form_tag('', name: 'form1', method: 'post', remote: true) do -%>
<%= hidden_field_tag('scaned_nos', "") %>
<%= hidden_field_tag('htmls', "") %>
<%= hidden_field_tag('num', 0) %>
<div>
	<table>
		<tr>
			<td><h4>已扫邮件数:<font color="red"><%= label_tag 'return_amount', 0, class: 'control-group', :id => "return_amount" %></h4></font></td>
		</tr>
		<tr>
			<td><h4>堆名: <%= text_field_tag 'batch_name', nil, size: "25", :id => "batch_name" %></h4></td>			
		</tr>
		<tr>
			<td><h4>邮件号: <%= text_field_tag 'express_no', nil, class: "controls showmask", size: "30", maxlength: 13, :id => "express_no", :disabled => false %></h4></td>
			<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td><%= button_tag "重置",:class => 'btn btn-primary', :id => "reset", :type => "button"%></td>
			<td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
			<td><%= button_tag "保存",:class => 'btn btn-primary', method: :post, :type => "button", :id => "return_save" %></td>
		</tr>
	</table>
</div>
<div id="out_results">
</div>
<% end %>

app/views/expresses/show.html.erb
<%- model_class = Express -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:express_no) %>:</strong></dt>
  <dd><%= @express.express_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:receiver_province) %>:</strong></dt>
  <dd><%= @express.receiver_province %></dd>
  <dt><strong><%= model_class.human_attribute_name(:receiver_city) %>:</strong></dt>
  <dd><%= @express.receiver_city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:receiver_district) %>:</strong></dt>
  <dd><%= @express.receiver_district %></dd>
  <dt><strong><%= model_class.human_attribute_name(:receiver_addr) %>:</strong></dt>
  <dd><%= @express.receiver_addr %></dd>
  <dt><strong><%= model_class.human_attribute_name(:receiver_name) %>:</strong></dt>
  <dd><%= @express.receiver_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:receiver_phone) %>:</strong></dt>
  <dd><%= @express.receiver_phone %></dd>
</dl>

<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_express_path(@express), :class => 'btn btn-default' %>
<%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            (params['referer'].blank? ? request.referer : params['referer']), :class => 'btn btn-default' %>