config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :user_logs, only: [:index, :show, :destroy]

  resources :units do
    collection do
      get 'import'
      post 'import' => 'units#import'
    end
    resources :users, :controller => 'unit_users'

    member do 
      # get 'index'
      get 'new_child_unit' => 'units#new'
      get 'child_units' => 'units#index'
      # get 'update_unit'
      # get 'destroy_unit'
    end
  end

  resources :users do
    member do
      get 'to_reset_pwd'
      patch 'reset_pwd'
      post 'lock' => 'users#lock'
      post 'unlock' => 'users#unlock'
    end
    resources :roles, :controller => 'user_roles'
  end

  resources :up_downloads do
    collection do 
      get 'up_download_import'
      post 'up_download_import' => 'up_downloads#up_download_import'
      
      get 'to_import'
      
      
    end
    member do
      get 'up_download_export'
      post 'up_download_export' => 'up_downloads#up_download_export'
    end
  end

  resources :expresses do
    collection do 
      get 'return_scan'
      post 'return_scan'
      post 'return_save'
      get 'resend_scan'
      post 'resend_scan'
      post 'find_resend_express_result'
      get 'tkzd'
      post 'tkzd'
      post 'get_new_express_no_and_print'
      get 'change_express_addr'
      post 'change_express_addr'
      get 'set_no_modify'
      post 'set_no_modify'
      get 'anomaly_done'
      post 'anomaly_done'
      get 'anomaly_index'
      post 'express_export'
      get 'set_failed'
      post 'set_failed'
    end
  end

  resources :batches do
    member do
      get 'done'
      post 'done' => 'batches#done'
    end
  end

  resources :orders do
    collection do 
      get 'change_order_addr'
      post 'change_order_addr'
      get 'set_no_modify'
      post 'set_no_modify'
    end
  end
    


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/up_download.rb
class UpDownload < ApplicationRecord
	validates_presence_of :name, :url, :message => '不能为空'

	def filename
		if self.url.split('/').last.rindex('.').blank?
      filename = self.url.split('/').last
    else
      filename_before = self.url.split('/').last[0,self.url.split('/').last.rindex('.')]
      filename_after = self.url.split('.').last
      filename = filename_before + '.' + filename_after
    end
	end

	def self.upload(file)
    if !file.original_filename.empty?
      direct = "#{Rails.root}/public/download/"
       
      if !File.exist?(direct)
        Dir.mkdir(direct)          
      end

      if file.original_filename.rindex('.').blank?
        filename = "#{Time.now.strftime("%Y-%m-%d %H:%M:%S")}_#{file.original_filename}"
      else
        filename_before = file.original_filename[0, file.original_filename.rindex('.')]
        filename_after = file.original_filename.split('.').last
        filename = "#{Time.now.strftime("%Y-%m-%d %H:%M:%S")}_#{filename_before+'.'+filename_after}"
      end

      file_path = direct + filename
    end
  end

  def self.write(file, file_path)
    File.open(file_path, "wb") do |f|
      f.write(file.read)
    end
  end
end

app/controllers/up_downloads_controller.rb
class UpDownloadsController < ApplicationController
  load_and_authorize_resource

  def index
    @up_downloads = initialize_grid(@up_downloads, order: 'created_at',order_direction: :desc)
     #@up_download = UpDownload.all
  end

  def show
    
  end

  def new
    #@up_download = UpDownload.new
    #respond_with(@up_download)
  end

  def edit
  end

  def create
    respond_to do |format|
      unless request.get?
        if ! params[:file].blank? && ! params[:file]['file'].blank?
          file  = params[:file]['file']
          @up_download = UpDownload.new(up_download_params)
          file_path = UpDownload.upload(file)       
      
          @up_download.url = file_path
          @up_download.oper_date = Time.now
          
          # redirect_to up_downloads_url
        end
      end
      if @up_download.save
        UpDownload.write(file, file_path)
        flash[:alert] = "上传成功"
        format.html { redirect_to up_downloads_url, notice: I18n.t('controller.create_success_notice', model: '模板') }
        format.json { render action: 'show', status: :created, location: @up_download}
      else
        format.html { render action: 'up_download_import' }
        format.json { render json: @up_download.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #@up_download.update(up_download_params)
    #respond_with(@up_download)
  end

  def destroy
    #@up_download.destroy
    #respond_with(@up_download)
    file_path = @up_download.url
    if File.exist?(file_path)
      File.delete(file_path)

      @up_download.destroy
    end
    respond_to do |format|
      format.html { redirect_to up_downloads_url }
      format.json { head :no_content }
    end
    
  end

  def to_import
    #redirect_to up_download_import_up_downloads_url
    @up_download = UpDownload.new
    render(:action => 'up_download_import')

  end

  
  def up_download_export
    up_download=UpDownload.find(params[:id])
    
    if up_download.nil?
       flash[:alert] = "无此文档模板"
       redirect_to :action => 'index'
    else
      file_path = up_download.url
      if File.exist?(file_path)
        io = File.open(file_path)
        # send_data(io.read,:filename => @up_download.name,:type => "text/excel;charset=utf-8; header=present", disposition: 'attachment')
        # send_data(io.read,:filename => filename,:type => "application/octet-stream", disposition: 'attachment')
        send_data(io.read,:filename => up_download.filename,:type => "text/excel;charset=utf-8; header=present", disposition: 'attachment')
        io.close
      else
        redirect_to up_downloads_path, :notice => '模板不存在，下载失败！'
      end
    end
  end

  private
    def set_up_download
      @up_download = UpDownload.find(params[:id])
    end

    def up_download_params
      params.require(:up_download).permit(:name, :use, :desc, :ver_no)
      
    end
end

app/views/up_downloads/_form.html.erb
<%= form_for(@up_download) do |f| %>
  <% if @up_download.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@up_download.errors.count, "error") %> prohibited this up_download from being saved:</h2>

      <ul>
      <% @up_download.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :use %><br>
    <%= f.text_field :use %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :ver_no %><br>
    <%= f.text_field :ver_no %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/up_downloads/edit.html.erb
<h1>Editing up_download</h1>

<%= render 'form' %>

<%= link_to 'Show', @up_download %> |
<%= link_to 'Back', up_downloads_path %>

app/views/up_downloads/index.html.erb
<%- model_class = UpDownload -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
<div style="float:right">
    <% if can? :to_import, UpDownload %>
      <%= link_to t('.import', :default => t("helpers.links.up_download_import")),
                  to_import_up_downloads_path,
                  :class => 'btn btn-primary' %>
      
    <% end %>
  </div>
</div>

<%= grid(@up_downloads, :show_filters => :always) do |g|
    
    g.column name: model_class.human_attribute_name(:name), attribute: 'name'

    g.column name: model_class.human_attribute_name(:use), attribute: 'use'

    g.column name: model_class.human_attribute_name(:desc), attribute: 'desc'

    g.column name: model_class.human_attribute_name(:ver_no), attribute: 'ver_no'


    g.column name: model_class.human_attribute_name(:oper_date), attribute: 'oper_date' do |up_download|
      l up_download.oper_date
    end

    g.column name: model_class.human_attribute_name(:created_at), attribute: 'created_at' do |up_download|
      l up_download.created_at
    end

    g.column do |up_download|
      ActiveSupport::SafeBuffer.new << 
      (link_to t('.export', :default => t("helpers.links.up_download_export")),
                      up_download_export_up_download_path(up_download),:method => 'post', :class => 'btn btn-xs btn-primary') << ' ' <<
        (link_to t('.destroy', :default => t("helpers.links.destroy")), up_download_path(up_download), :method => :delete, :data => { :confirm => t('wice_grid.saved_query_deletion_confirmation', :default => t("helpers.links.confirm", :default => '确定删除?')) }, :class => 'btn btn-xs btn-danger' if can? :destroy, up_download)


    end 
  end 
%>

app/views/up_downloads/new.html.erb
<h1>New up_download</h1>

<%= render 'form' %>

<%= link_to 'Back', up_downloads_path %>

app/views/up_downloads/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_up_download_path(@up_download) %> |
<%= link_to 'Back', up_downloads_path %>

app/views/up_downloads/up_download_import.html.erb
<%- model_class = UpDownload -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<%= form_for @up_download, :html => { :class => 'form-horizontal',:action => 'up_download_import',:multipart => true } do |f| %>

  <% 
  @up_download.errors.full_messages.each do |msg| 
  %>
      <li><%= msg %></li>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <font color="red">(必填)</font>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :use, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :use, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :desc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :desc, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ver_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ver_no, :class => 'text_field' %>
    </div>
  </div>


  <div class="controls">
  <font size=2><b>上传文档模板 </b><font color="red">(必选)</font><%= file_field("file", "file",onclick: "$('#submit_button').removeAttr('disabled');") %>
  </font>   
 </div>
  
  <br>

  <%= submit_tag "确认导入",:id=>'submit_button',:disabled=> 'disabled', onclick: "form1.submit();this.disabled='disabled';", :class => 'btn btn-primary' %>
  <!--<%= submit_tag "确认导入", data: { disable_with: "导入中，请稍等..." } %>-->
  

<% end %>